---


- name: Install nginx package
  package: name=nginx state=present


- name: Ensure nginx dhparams_path folder
  file: state=directory path={{ nginx_https_dhparam_path | dirname }}

- name: Create secure Ephemeral Diffie-Hellman parameter
  shell: openssl dhparam -out {{ nginx_https_dhparam_path }} {{ nginx_https_dhparam_size }}
  args:
    creates: "{{ nginx_https_dhparam_path }}"


- name: Remove potential dupplicate ssl_prefer_server_ciphers
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '.*ssl_prefer_server_ciphers.*'
    state: absent
- name: Remove potential dupplicate ssl_protocols
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '.*ssl_protocols.*'
    state: absent

- name: Deploy tls config for nginx
  template:
    src: templates/tls.conf.j2
    dest: /etc/nginx/conf.d/tls.conf
  notify: Restart nginx


- name: Remove default nginx config
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Deploy nginx http config
  template:
    src: templates/http.conf.j2
    dest: /etc/nginx/sites-available/http.conf
  notify: Restart nginx

- name: Enable nginx http config
  file:
    src: /etc/nginx/sites-available/http.conf
    dest: /etc/nginx/sites-enabled/http.conf
    state: link
  notify: Restart nginx


- name: Ensure nginx is started and runs on startup.
  service: name=nginx state=started enabled=yes
